import { Inter } from "next/font/google";
import "@/app/globals.css";
import MainHeader from "@/components/main-header/ManHeader";
import MainHeaderBackground from "@/components/main-header/main-header-background";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="h-screen">
        <MainHeader />
        {children}
      </body>
    </html>
  );
}
